#ifndef MAGIC_CONSTANTS_HPP
#define MAGIC_CONSTANTS_HPP

#ifndef CONST_VERT_SIZES
#define CONST_VERT_SIZES { 1, 2, 2, 2, 3, 4, 4, 7, 4, 1 }
#endif 

#ifndef CONST_TRIES_AFTER_RESET
#define CONST_TRIES_AFTER_RESET 20
#endif 

#ifndef CONST_STAR_CONTRACTIONS_TIME
#define CONST_STAR_CONTRACTIONS_TIME (10*60)
#endif

#ifndef CONST_STOP_CONTRACTIONS_AT_NUMBER_TERMINALS
#define CONST_STOP_CONTRACTIONS_AT_NUMBER_TERMINALS 1
#endif

#ifndef CONST_ABOVE_CURRENT_WEIGHT
#define CONST_ABOVE_CURRENT_WEIGHT 1.001
#endif

#endif // MAGIC_CONSTANTS_HPP
